Remove references of mercator tool
thoth-station/package-extract pull request #487
Opened 2022-07-22 18:39 UTC by shreekarSS

Signed-off-by: Shreekara <sshreeka@redhat.com>

## Related Issues and Dependencies
Fixes: https://github.com/thoth-station/package-extract/issues/485
…

## Description
Remove all references of mercator from package-extract repo

2022-07-22 18:40 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **sesheta** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @sesheta` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fpackage-extract).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/package-extract/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["sesheta"]} -->

2022-07-22 18:40 UTC, sesheta commented
@shreekarSS: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | 2150e05007f51a72087cd333f6263c5bc8b1459b | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_package-extract/487/pre-commit/1550551316542001152) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=package-extract&pr=487). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AshreekarSS). Please help us and [open an issue](https://github.com/thoth-station/package-extract/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-07-25 11:28 UTC, mayaCostantini reviewed
lgtm, just a few comments :+1: 
Have you tested extracting dependencies from an image with those changes (with the CLI)?

2022-07-25 11:28 UTC, mayaCostantini commented on README.rst
> -      },
I think the `"mercator"` field goes until ~L810, could you remove the rest of it from this example?

2022-07-28 15:35 UTC, shreekarSS commented on CHANGELOG.md
> -* Mercator can output None
ack

2022-07-28 15:49 UTC, mayaCostantini approved these changes
Very good :100: Let's have this in

2022-07-28 15:49 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/thoth-station/package-extract/pull/487#pullrequestreview-1054370134" title="Approved">mayaCostantini</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **sesheta** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @sesheta` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fpackage-extract).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/package-extract/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["sesheta"]} -->

2022-07-28 15:58 UTC, mayaCostantini commented
/approve

2022-07-28 16:01 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/thoth-station/package-extract/pull/487#issuecomment-1198342287" title="Approved">mayaCostantini</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fpackage-extract).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/thoth-station/package-extract/blob/master/OWNERS)~~ [mayaCostantini]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-07-28 17:10 UTC, harshad16 requested changes
please include `kubernetes~=12.0.1` in the requirements.txt to fix build issue.
/hold

2022-07-28 17:11 UTC, harshad16 commented
Please rebase as well
keep the pr to one commit, if possible.

2022-07-28 17:32 UTC, sesheta commented
@shreekarSS: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pytest | f46d24f47764cc3173b6dda0bac5ebc5b456e499 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_package-extract/487/thoth-pytest-py38/1552708219757924352) | true | `/test thoth-pytest-py38`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=package-extract&pr=487). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AshreekarSS). Please help us and [open an issue](https://github.com/thoth-station/package-extract/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-07-28 17:48 UTC, sesheta commented
@shreekarSS: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pytest | b7ff51deb1b9193a0a1a6dae6d5f3074cf9d2e4f | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_package-extract/487/thoth-pytest-py38/1552712368344010752) | true | `/test thoth-pytest-py38`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=package-extract&pr=487). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AshreekarSS). Please help us and [open an issue](https://github.com/thoth-station/package-extract/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-07-28 17:49 UTC, shreekarSS commented
> please include `kubernetes~=12.0.1` in the requirements.txt to fix build issue. /hold

Thanks , fixed

2022-07-28 18:13 UTC, harshad16 commented
/unhold

2022-07-28 18:15 UTC, merged